repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
- repo: local
  hooks:
  - id: check-markdown
    name: Check the markdown files for inconsistencies.
    entry: ./tools/check-docs.sh
    language: system
    files: ".md"
  - id: check-file-names
    name: Check the file names for inconsistencies.
    entry: ./check-file-names.sh
    language: system
