name: Update Documentation
on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  check_markdown_syntax:
    name: Check markdown syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install markdownlint
        run: |
          gem install mdl
      - name: Lint docs
        run: |
          ./check-docs.sh
  build:
    name: Build
    needs: check_markdown_syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: rucio/rucio
          ref: master
          path: rucio
      - name: Install rucio-api generation dependencies and build markdown sites for the API
        env:
          RUCIO_TARGET_OVERRIDE: auto
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install -U -r requirements.txt
          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          ./rucio-generate-doc.py
          docker logout https://docker.pkg.github.com
      - name: Cache yarn packages
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            website/yarn.lock
            website/node_modules
      - name: Install dependencies and static website
        run: |
          cd website
          yarn install
          yarn build
      - uses: actions/upload-artifact@master
        with:
          name: documentation-artifacts
          path: website/build
  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: documentation-artifacts
          path: website/build
      - name: Push to Github Pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./publish.sh
